// Helpers: start-of-today -> YYYY-MM-DD, and day-offset generator
const formatYMD = (d: Date) =>
    `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;

const d = (offset = 0) => {
    const t = new Date();
    t.setHours(0, 0, 0, 0);
    t.setDate(t.getDate() + offset);
    return formatYMD(t);
};

// Offsets map: 11-04 → d(0), 11-05 → d(1), 11-06 → d(2), 11-07 → d(3),
// 11-08 → d(4), 11-09 → d(5), 11-10 → d(6)

export const resourceData = [
    {
        id: 1,
        name: "Alice Johnson",
        avatar: "https://randomuser.me/api/portraits/women/11.jpg",
        events: [
            {
                id: 101,
                resourceId: 1,
                from: 8 * 60,
                to: 9 * 60,
                title: "Physical Therapy",
                description: "Post-surgery recovery session",
                meta: { status: 5, preferred: true, note: "High-priority recovery client with weekly check-ins." },
                date: d(0),
            },
            {
                id: 103,
                resourceId: 1,
                from: 8 * 60 + 45,
                to: 9 * 60 + 30,
                title: "PT Follow-up",
                description: "Overlap to test conflict handling",
                meta: { status: 2, preferred: false, note: "Double-booked slot for conflict testing." },
                date: d(1),
            },
            {
                id: 102,
                resourceId: 1,
                from: 10 * 60,
                to: 11 * 60,
                title: "Mobility Assessment",
                description: "Initial consultation",
                meta: { status: 3, preferred: false },
                date: d(2),
            },
            {
                id: 104,
                resourceId: 1,
                from: 10 * 60 + 30,
                to: 11 * 60 + 30,
                title: "Gait Analysis",
                description: "Overlapping with assessment",
                meta: { status: 4, preferred: true, note: "Intended overlap for triage." },
                date: d(3),
            },
        ],
        disabledBlocks: [
            { id: 1001, resourceId: 1, from: 12 * 60, to: 13 * 60, title: "Lunch Break", date: d(4) },
        ],
        disableIntervals: [{ resourceId: 1, from: 17 * 60, to: 24 * 60, date: d(5) }],
    },
    {
        id: 2,
        name: "Bob Martinez",
        avatar: "https://randomuser.me/api/portraits/men/22.jpg",
        events: [
            {
                id: 201,
                resourceId: 2,
                from: 9 * 60 + 30,
                to: 10 * 60 + 30,
                title: "Personal Training",
                meta: {
                    status: 4,
                    preferred: true,
                    note: "Client focusing on weight loss — adjust cardio intensity.",
                },
                date: d(6),
            },
            {
                id: 202,
                resourceId: 2,
                from: 15 * 60,
                to: 16 * 60,
                title: "Endurance Coaching",
                meta: { status: 2, preferred: false },
                date: d(0),
            },
            {
                id: 203,
                resourceId: 2,
                from: 15 * 60 + 15,
                to: 16 * 60 + 15,
                title: "VO₂ Max Test",
                meta: { status: 5, preferred: true, note: "Intentional overlap with coaching." },
                date: d(1),
            },
        ],
        disabledBlocks: [{ id: 2001, resourceId: 2, from: 13 * 60, to: 14 * 60, title: "Staff Meeting", date: d(2) }],
        disableIntervals: [{ resourceId: 2, from: 7 * 60, to: 8 * 60, date: d(3) }],
    },
    {
        id: 3,
        name: "Charlie Kim",
        avatar: "https://randomuser.me/api/portraits/men/33.jpg",
        events: [
            {
                id: 301,
                resourceId: 3,
                from: 11 * 60,
                to: 12 * 60,
                title: "Sports Massage",
                meta: { status: 1, preferred: true, note: "Repeat client — shoulder strain recovery." },
                date: d(4),
            },
            {
                id: 303,
                resourceId: 3,
                from: 11 * 60 + 30,
                to: 12 * 60 + 30,
                title: "Trigger Point Therapy",
                meta: { status: 3, preferred: false, note: "Overlaps lunch slightly." },
                date: d(5),
            },
            {
                id: 302,
                resourceId: 3,
                from: 14 * 60 + 15,
                to: 15 * 60,
                title: "Deep Tissue Massage",
                meta: { status: 5, preferred: false, note: "Requested deeper pressure than usual." },
                date: d(6),
            },
        ],
        disabledBlocks: [{ id: 3001, resourceId: 3, from: 12 * 60, to: 13 * 60, title: "Lunch", date: d(0) }],
        disableIntervals: [],
    },
    {
        id: 4,
        name: "Diana Ross",
        avatar: "https://randomuser.me/api/portraits/women/44.jpg",
        events: [
            {
                id: 401,
                resourceId: 4,
                from: 13 * 60,
                to: 14 * 60,
                title: "Nutrition Plan Review",
                description: "Discuss dietary adjustments",
                meta: { status: 4, preferred: true, note: "Client transitioning to a new macro plan." },
                date: d(1),
            },
            {
                id: 402,
                resourceId: 4,
                from: 13 * 60 + 30,
                to: 14 * 60 + 30,
                title: "Supplement Consultation",
                description: "Overlap to test scheduler",
                meta: { status: 2, preferred: false, note: "Partial overlap intended." },
                date: d(2),
            },
        ],
        disabledBlocks: [],
        disableIntervals: [{ resourceId: 4, from: 18 * 60, to: 24 * 60, date: d(3) }],
    },
    {
        id: 5,
        name: "Evan Lee",
        avatar: "https://randomuser.me/api/portraits/men/55.jpg",
        events: [
            {
                id: 501,
                resourceId: 5,
                from: 17 * 60,
                to: 18 * 60,
                title: "Evening Yoga",
                description: "Beginner-level class",
                meta: { status: 2, preferred: true, note: "Full class expected; ensure space availability." },
                date: d(4),
            },
            {
                id: 502,
                resourceId: 5,
                from: 17 * 60 + 15,
                to: 17 * 60 + 45,
                title: "One-on-One Yoga Intro",
                description: "Intentional overlap with group class",
                meta: { status: 3, preferred: false, note: "Short overlapping session." },
                date: d(5),
            },
        ],
        disabledBlocks: [
            { id: 5001, resourceId: 5, from: 12 * 60 + 30, to: 13 * 60 + 30, title: "Lunch Break", date: d(6) },
        ],
        disableIntervals: [],
    },
    {
        id: 6,
        name: "Fatima Noor",
        avatar: "https://randomuser.me/api/portraits/women/66.jpg",
        events: [
            {
                id: 601,
                resourceId: 6,
                from: 9 * 60,
                to: 10 * 60,
                title: "Pilates Session",
                description: "Core stability focus",
                meta: { status: 3, preferred: true, note: "Client recovering from lower back pain." },
                date: d(0),
            },
            {
                id: 602,
                resourceId: 6,
                from: 9 * 60 + 30,
                to: 10 * 60 + 30,
                title: "Reformer Intro",
                description: "Overlap to simulate double-booking",
                meta: { status: 5, preferred: false, note: "New client; may reschedule." },
                date: d(1),
            },
            {
                id: 603,
                resourceId: 6,
                from: 16 * 60,
                to: 17 * 60 + 30,
                title: "Injury Prevention Workshop",
                meta: { status: 4, preferred: true, note: "Team session; room booking required." },
                date: d(2),
            },
        ],
        disabledBlocks: [{ id: 6001, resourceId: 6, from: 12 * 60, to: 12 * 60 + 30, title: "Break", date: d(3) }],
        disableIntervals: [{ resourceId: 6, from: 19 * 60, to: 24 * 60, date: d(4) }],
    },
    {
        id: 7,
        name: "George Patel",
        avatar: "https://randomuser.me/api/portraits/men/77.jpg",
        events: [
            {
                id: 701,
                resourceId: 7,
                from: 10 * 60,
                to: 11 * 60,
                title: "Strength Screening",
                meta: { status: 2, preferred: true, note: "Baseline measurements." },
                date: d(5),
            },
            {
                id: 702,
                resourceId: 7,
                from: 10 * 60 + 45,
                to: 12 * 60,
                title: "Kettlebell Clinic",
                meta: { status: 5, preferred: false, note: "Overlaps screening; conflict edge case." },
                date: d(6),
            },
            {
                id: 703,
                resourceId: 7,
                from: 11 * 60 + 30,
                to: 12 * 60 + 30,
                title: "Functional Movement Test",
                meta: { status: 1, preferred: false, note: "Second overlap creating a chain." },
                date: d(0),
            },
        ],
        disabledBlocks: [{ id: 7001, resourceId: 7, from: 13 * 60, to: 13 * 60 + 30, title: "Admin Time", date: d(1) }],
        disableIntervals: [{ resourceId: 7, from: 18 * 60, to: 24 * 60, date: d(2) }],
    },
];
